---
spring:
  profiles:
    active: prod
  output:
    ansi:
      enabled: detect

---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 0
    maxWait: 3600
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: false
#    maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halo?useSSL=false&autoReconnect=true
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  session:
    store-type: none
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090
  tomcat:
    min-spare-threads: 20
    max-threads: 100
    max-connections: 5000
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

---
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 0
    maxWait: 3600
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: false
#    maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halo?useSSL=false&autoReconnect=true
    username: root
    password: password
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  session:
    store-type: none
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090
  tomcat:
    min-spare-threads: 20
    max-threads: 100
    max-connections: 5000
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
